### PR TITLE
Upgrade orchestra/testbench to 4.x

### PR DESCRIPTION
**Pull request by asbiin**
Upgrade orchestra/testbench to 4.x so this is compatible with Laravel 6.x

### CODE REVIEW

**Comment by asbiin** [comment]
@muglug Hi! Any update with this PR? Thanks!

**Comment by muglug** [comment]
Sorry! Update is, it’s merged

**Comment by asbiin** [comment]
Great! Thank you :)
Can't wait for the next release 👍

**Comment by muglug** [comment]
There's a new release!

**Pull request merged**
